spring:
  datasource:
    url: jdbc:mysql://localhost:3307/login-app
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    mode=HTML: